'use client' //usepathnameを使用するために記述
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'
import Header from '@/components/organisms/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App', //"kstm-LTplatform"とかに変更？
  description: 'Generated by create next app',
}

// appディレクトリ下のpage.tsx(ログインページ)のみ，ヘッダーを適用しない
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()
  const isRootPage = pathname === '/'

  return (
    <html lang="en">
      <body className={inter.className}>
        {!isRootPage && <Header logoSrc="./images/kstm.png" logoAlt="hero" />}
        {children}
      </body>
    </html>
  )
}
