import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from '../context/AuthProvider'
import Header from '@/components/organisms/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App', //"kstm-LTplatform"とかに変更？
  description: 'Generated by create next app',
}

// ログインページ(appディレクトリ下のpage.tsx)のみ，ヘッダーを適用しない
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <Header logoSrc="../images/kstm.png" logoAlt="headerLogo" />
      {children}
    </AuthProvider>
  )
}
